import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import { test } from "node:test";

const packageJson = JSON.parse(readFileSync(new URL("../package.json", import.meta.url), "utf8"));
const packageLockJson = JSON.parse(readFileSync(new URL("../package-lock.json", import.meta.url), "utf8"));
const readme = readFileSync(new URL("../README.md", import.meta.url), "utf8");
const usageGuide = readFileSync(new URL("../docs/usage.md", import.meta.url), "utf8");
const changelog = readFileSync(new URL("../CHANGELOG.md", import.meta.url), "utf8");
const provenanceGuide = readFileSync(new URL("../docs/provenance-and-licenses.md", import.meta.url), "utf8");
const releaseGuide = readFileSync(new URL("../docs/release-checklist.md", import.meta.url), "utf8");
const whyMaqam = readFileSync(new URL("../docs/why-maqam.md", import.meta.url), "utf8");
const integrations = readFileSync(new URL("../docs/integrations.md", import.meta.url), "utf8");
const comparison = readFileSync(new URL("../docs/comparison.md", import.meta.url), "utf8");
const benchmarking = readFileSync(new URL("../docs/benchmarking.md", import.meta.url), "utf8");
const quickstart = readFileSync(new URL("../docs/quickstart.md", import.meta.url), "utf8");
const governedSources = readFileSync(new URL("../docs/governed-sources.md", import.meta.url), "utf8");
const anonymousPublicSources = readFileSync(new URL("../docs/anonymous-public-sources.md", import.meta.url), "utf8");
const migration03 = readFileSync(new URL("../docs/migration-0.3.md", import.meta.url), "utf8");
const release03 = readFileSync(new URL("../docs/release-0.3.0.md", import.meta.url), "utf8");
const release031 = readFileSync(new URL("../docs/release-0.3.1.md", import.meta.url), "utf8");
const rootReleaseGuide = readFileSync(new URL("../RELEASE_CHECKLIST.md", import.meta.url), "utf8");
const roadmap = readFileSync(new URL("../ROADMAP.md", import.meta.url), "utf8");
const technicalArticle = readFileSync(new URL("../docs/articles/exact-agent-approvals.md", import.meta.url), "utf8");
const maqamBin = readFileSync(new URL("../bin/maqam.js", import.meta.url), "utf8");
const security = readFileSync(new URL("../SECURITY.md", import.meta.url), "utf8");
const licenseAudit = readFileSync(new URL("../LICENSE_AUDIT.md", import.meta.url), "utf8");
const publishingGuide = readFileSync(new URL("../.github/PUBLISHING.md", import.meta.url), "utf8");
const ciWorkflow = readFileSync(new URL("../.github/workflows/ci.yml", import.meta.url), "utf8");
const publishWorkflow = readFileSync(new URL("../.github/workflows/publish-npm.yml", import.meta.url), "utf8");

test("package metadata is ready for Maqam npm publishing", () => {
  assert.equal(packageJson.name, "maqam");
  assert.equal(packageJson.version, "0.3.1");
  assert.equal(packageLockJson.version, "0.3.1");
  assert.equal(packageLockJson.packages[""].version, "0.3.1");
  assert.equal(packageJson.license, "MIT");
  assert.equal(packageJson.author, "Ajnas NB");
  assert.match(packageJson.description, /governed web search/i);
  assert.match(packageJson.description, /YouTube metadata and captions/i);
  assert.equal(packageJson.type, "module");
  assert.equal(packageJson.sideEffects, false);
  assert.equal(packageJson.types, "src/index.d.ts");
  assert.equal(packageJson.bin.maqam, "bin/maqam.js");
  assert.equal(packageJson.bin["maqam-crawl"], "bin/ajnas-crawl.js");
  assert.equal(packageJson.repository.url, "git+https://github.com/AjnasNB/maqam.git");
  assert.equal(packageJson.publishConfig.access, "public");
  assert.equal(packageJson.exports["./server"].types, "./src/maqam/server.d.ts");
  assert.equal(packageJson.exports["./server"].default, "./src/maqam/server.js");
  assert.ok(packageJson.files.includes("app/index.html"));
  assert.ok(packageJson.files.includes("app/app.js"));
  assert.ok(packageJson.files.includes("app/styles.css"));
  assert.ok(packageJson.files.includes("app/assets/maqam-logo.svg"));
  assert.equal(packageJson.files.includes("app/"), false);
  assert.ok(packageJson.files.includes("src/"));
  assert.ok(packageJson.files.includes("docs/usage.md"));
  assert.ok(packageJson.files.includes("docs/external-agents.md"));
  assert.ok(packageJson.files.includes("docs/release-checklist.md"));
  assert.ok(packageJson.files.includes("docs/provenance-and-licenses.md"));
  assert.ok(packageJson.files.includes("docs/comparison.md"));
  assert.ok(packageJson.files.includes("docs/benchmarking.md"));
  assert.ok(packageJson.files.includes("docs/quickstart.md"));
  assert.ok(packageJson.files.includes("docs/why-maqam.md"));
  assert.ok(packageJson.files.includes("docs/integrations.md"));
  assert.ok(packageJson.files.includes("docs/articles/exact-agent-approvals.md"));
  assert.ok(packageJson.files.includes("docs/articles/benchmarking-agent-governance.md"));
  assert.ok(packageJson.files.includes("docs/migration-0.2.md"));
  assert.ok(packageJson.files.includes("docs/migration-0.3.md"));
  assert.ok(packageJson.files.includes("docs/governed-sources.md"));
  assert.ok(packageJson.files.includes("docs/anonymous-public-sources.md"));
  assert.ok(packageJson.files.includes("docs/release-0.3.0.md"));
  assert.ok(packageJson.files.includes("docs/release-0.3.1.md"));
  assert.ok(packageJson.files.includes("examples/"));
  assert.ok(packageJson.files.includes("benchmarks/"));
  assert.ok(packageJson.files.includes("ROADMAP.md"));
  assert.ok(packageJson.files.includes("CHANGELOG.md"));
  assert.ok(packageJson.files.includes("SECURITY.md"));
  assert.ok(packageJson.files.includes("RELEASE_CHECKLIST.md"));
  assert.ok(packageJson.files.includes("LICENSE_AUDIT.md"));
  assert.ok(packageJson.keywords.includes("agent-framework"));
  assert.ok(packageJson.keywords.includes("governance"));
  assert.ok(packageJson.keywords.includes("release-gate"));
  assert.ok(packageJson.keywords.includes("source-router"));
  assert.ok(packageJson.keywords.includes("agent-governance"));
  assert.ok(packageJson.keywords.includes("research-agent"));
  assert.ok(packageJson.keywords.includes("web-search"));
  assert.ok(packageJson.keywords.includes("mcp"));
  assert.ok(packageJson.keywords.includes("youtube"));
  assert.ok(packageJson.keywords.includes("youtube-captions"));
  assert.ok(packageJson.keywords.includes("yt-dlp"));
  assert.ok(packageJson.keywords.includes("rss"));
  assert.equal(packageJson.dependencies["ipaddr.js"], "^2.4.0");
  assert.equal(packageJson.dependencies["@types/node"], "^20.19.43");
  assert.equal(packageJson.devDependencies.typescript, "^5.9.3");
  assert.match(packageJson.scripts.prepublishOnly, /test:consumer-types/);
  assert.equal(packageJson.scripts["demo:approval"], "node bin/maqam.js demo approval");
  assert.equal(packageJson.scripts["benchmark:governance"], "node benchmarks/governance-overhead.mjs");
  assert.equal(packageJson.scripts["benchmark:mges:performance"], "node benchmarks/governance-suite.mjs");
  assert.equal(packageJson.scripts["benchmark:mges:conformance"], "node benchmarks/governance-conformance.mjs");
  assert.equal(packageJson.dependencies.undici, "^7.28.0");
  assert.equal(packageJson.engines.node, ">=20.18.1");
});

test("public docs and brand assets match Maqam identity", () => {
  assert.match(readme, /^# Maqam/m);
  assert.match(readme, /maqam-readme-hero\.png/);
  assert.match(readme, /maqam-system-map\.svg/);
  assert.match(readme, /maqam-cli-agent-flow\.png/);
  assert.match(readme, /Full documentation/);
  assert.match(readme, /Release checklist/);
  assert.match(readme, /Provenance and license notes/);
  assert.match(readme, /npm install -g maqam/);
  assert.match(readme, /MIT/);
  assert.match(usageGuide, /^# Maqam Usage Guide/m);
  assert.match(usageGuide, /AgentRuntime/);
  assert.match(usageGuide, /PolicyEngine/);
  assert.match(usageGuide, /Universal Agent Control/);
  assert.match(usageGuide, /Control Any Agent/);
  assert.match(usageGuide, /Control CLI Workers/);
  assert.match(usageGuide, /createAgentTool/);
  assert.match(usageGuide, /createCliAgentTool/);
  assert.match(usageGuide, /ApprovalQueue/);
  assert.match(usageGuide, /createReleaseGateReport/);
  assert.match(whyMaqam, /^# Why Maqam/m);
  assert.match(whyMaqam, /canonical/i);
  assert.match(comparison, /Microsoft Agent Governance Toolkit/);
  assert.match(benchmarking, /Maqam Governance Evaluation Suite/);
  assert.match(benchmarking, /not a globally standardized benchmark/);
  assert.match(quickstart, /^# Maqam Five-Minute Quickstart/m);
  assert.match(quickstart, /npm uninstall -g maqam/);
  assert.match(integrations, /runToolAdapterConformance/);
  assert.match(integrations, /does not bundle provider SDKs/);
  assert.match(integrations, /Governed source adapters/);
  assert.match(governedSources, /^# Governed Sources/m);
  assert.match(governedSources, /routeUngoverned\(\)/);
  assert.match(governedSources, /Independent Connector Boundary/);
  assert.match(anonymousPublicSources, /^# Anonymous-Public Source Pack/m);
  assert.match(anonymousPublicSources, /createExaSearchSourceAdapter/);
  assert.match(anonymousPublicSources, /createYtDlpYouTubeSourceAdapter/);
  assert.match(anonymousPublicSources, /not a promise of unrestricted access/i);
  assert.match(migration03, /^# Migrating To Maqam 0\.3/m);
  assert.match(migration03, /--allowed-origin/);
  assert.match(release03, /^# Maqam 0\.3\.0 Release Record/m);
  assert.match(release03, /published and registry-verified/i);
  assert.match(release03, /98c2d97dc31495ec30a0b44c5016fd76316c2074/i);
  assert.match(release03, /sha512-0fV354AKT6JtVMYzWcMCfjUQpJHIjaNF\+bGjxq8TzcuElNVQsx3Cp5Yc062RgNJ5zSDVgUJSn1hzn04hT3jWuQ==/i);
  assert.match(release031, /^# Maqam 0\.3\.1 Release Record/m);
  assert.match(release031, /Lifecycle:\*\* registry-defined/i);
  assert.match(release031, /live npm record[\s\S]{0,180}matching `v0\.3\.1` tag/i);
  assert.match(readme, /Previous verified release:[\s\S]{0,240}maqam@0\.3\.0/i);
  assert.match(readme, /0\.3\.1 release line/i);
  assert.match(readme, /npm view maqam@0\.3\.1 version gitHead dist\.integrity/i);
  assert.match(readme, /Until both records exist and identify the same reviewed commit, treat 0\.3\.1 as unavailable/i);
  assert.match(readme, /0\.3 release line/i);
  assert.match(readme, /hosted-anonymous Exa web search/i);
  assert.match(readme, /public YouTube metadata and available captions/i);
  assert.match(readme, /npm view maqam dist-tags\.latest gitHead dist\.integrity/i);
  assert.match(readme, /historical 0\.2\.4 release/i);
  assert.doesNotMatch(readme, /maqam@0\.2\.3[^\n]*latest public npm package/i);
  assert.doesNotMatch(readme, /0\.2\.4 is a candidate/i);
  assert.doesNotMatch(readme, /(?:Maqam |maqam@|v)?0\.3\.0 (?:release )?candidate/i);
  assert.doesNotMatch(readme, /`maqam@0\.3\.0` \(after exact registry verification\)/i);
  assert.match(quickstart, /npx -y maqam@0\.3\.1 demo approval/);
  assert.doesNotMatch(quickstart, /maqam@0\.2\.4/);
  assert.match(comparison, /OpenAI Agents SDK/);
  assert.match(comparison, /LangGraph/);
  assert.match(roadmap, /^# Maqam Public Roadmap/m);
  assert.match(technicalArticle, /approval may not authorize the input/i);
  assert.match(maqamBin, /startMaqamServer/);
  assert.match(maqamBin, /--allow-private-networks/);
  assert.match(maqamBin, /--allowed-ui-origin/);
  assert.match(maqamBin, /MAQAM_API_TOKEN/);
  assert.match(maqamBin, /demo approval/);
  assert.ok(existsSync(new URL("../benchmarks/governance-overhead.mjs", import.meta.url)));
  assert.ok(existsSync(new URL("../benchmarks/governance-suite.mjs", import.meta.url)));
  assert.ok(existsSync(new URL("../benchmarks/governance-conformance.mjs", import.meta.url)));
  assert.ok(existsSync(new URL("../src/index.d.ts", import.meta.url)));
  assert.ok(existsSync(new URL("../examples/governed-release.mjs", import.meta.url)));
  assert.ok(existsSync(new URL("../examples/govern-coding-agent.mjs", import.meta.url)));
  assert.ok(existsSync(new URL("../examples/govern-approved-write.mjs", import.meta.url)));
  assert.ok(existsSync(new URL("../examples/tool-adapter-ecosystem.mjs", import.meta.url)));
  assert.ok(existsSync(new URL("../examples/governed-sources.mjs", import.meta.url)));
  assert.ok(existsSync(new URL("../docs/external-agents.md", import.meta.url)));
  assert.ok(existsSync(new URL("../app/assets/maqam-logo.svg", import.meta.url)));
  assert.ok(existsSync(new URL("../app/assets/maqam-brand-board.png", import.meta.url)));
  assert.ok(existsSync(new URL("../app/assets/maqam-readme-hero.png", import.meta.url)));
  assert.ok(existsSync(new URL("../app/assets/maqam-system-map.svg", import.meta.url)));
  assert.ok(existsSync(new URL("../app/assets/maqam-cli-agent-flow.png", import.meta.url)));
});

test("release governance docs require approval before publishing", () => {
  assert.match(changelog, /^# Changelog/m);
  assert.match(changelog, /## 0\.3\.1\n/);
  assert.match(changelog, /## 0\.3\.0 - 2026-07-18/);
  assert.match(changelog, /## 0\.2\.4 - 2026-07-17/);
  assert.match(changelog, /## 0\.2\.1 - 2026-07-15/);
  assert.match(changelog, /Fail-closed governance/);
  assert.match(releaseGuide, /^# Maqam Release Checklist/m);
  assert.match(releaseGuide, /npm test/);
  assert.match(releaseGuide, /npm pack --dry-run/);
  assert.match(releaseGuide, /npm publish --access public --ignore-scripts --provenance/);
  assert.match(releaseGuide, /explicit maintainer approval/);
  assert.match(provenanceGuide, /^# Provenance and License Notes/m);
  assert.match(provenanceGuide, /original Ajnas NB implementation/i);
  assert.match(provenanceGuide, /No source code[\s\S]*was copied into Maqam/i);
  assert.match(provenanceGuide, /ipaddr\.js/);
  assert.match(provenanceGuide, /undici/);
  assert.match(provenanceGuide, /Qwen-Agent/);
  assert.match(provenanceGuide, /PageAgent/);
  assert.match(provenanceGuide, /Agent Reach/);
  assert.match(provenanceGuide, /1494c2ab239e7355a77e7cceaf3271453a1f34b5/);
  assert.match(provenanceGuide, /Optional External Integrations/);
  assert.match(provenanceGuide, /yt-dlp/);
  assert.match(provenanceGuide, /does not download, update, vendor, or redistribute it/i);
  assert.match(licenseAudit, /Optional External Source Boundaries/);
  assert.match(licenseAudit, /No Exa SDK, server source, credentials, or branding is bundled/i);
  assert.match(licenseAudit, /Maqam never installs or redistributes `yt-dlp`/i);
  assert.match(provenanceGuide, /MIT/);
  assert.match(releaseGuide, /artifactFilename/);
  assert.match(releaseGuide, /artifactSizeBytes/);
  assert.match(releaseGuide, /artifactIntegrity/);
  assert.match(releaseGuide, /Previous Completed Release At Candidate Preparation[\s\S]{0,180}0\.3\.0[\s\S]{0,120}published on npm/i);
  assert.match(releaseGuide, /Release Target[\s\S]{0,180}0\.3\.1[\s\S]{0,160}candidate until protected publication completes/i);
  assert.match(releaseGuide, /maqam@0\.3\.1/);
  assert.match(releaseGuide, /trusted-publishing/i);
  assert.match(rootReleaseGuide, /release gate for `maqam@0\.3\.1`/i);
  assert.match(rootReleaseGuide, /live registry and matching GitHub release define its status/i);
  assert.match(rootReleaseGuide, /Version: `0\.3\.1`/i);
  assert.match(publishingGuide, /release-manifest\.json/);
  assert.match(publishingGuide, /full `gitCommit`/);
  assert.match(ciWorkflow, /Prepare exact npm candidate identity/);
  assert.match(ciWorkflow, /artifactSha256/);
  assert.match(ciWorkflow, /gitCommit/);
  assert.match(ciWorkflow, /npm@12\.0\.1/);
  assert.match(publishWorkflow, /expected_git_commit/);
  assert.match(publishWorkflow, /GITHUB_SHA[^\n]+EXPECTED_GIT_COMMIT/);
  assert.match(publishWorkflow, /expected_sha256/);
  assert.match(publishWorkflow, /expected_integrity/);
  assert.match(publishWorkflow, /default: 0\.3\.1/);
  assert.match(publishWorkflow, /npm audit signatures/);
  assert.match(security, /^# Security Policy/m);
  assert.match(security, /approval/i);
  assert.match(security, /integrity-protected trusted state/i);
  assert.match(security, /does not authenticate approvals/i);
});
